#!/bin/sh
set -e

cd backend

echo [pre-commit] Validando sintaxis PHP... && php -l app/Http/Controllers/MeasureController.php && php -l app/Http/Controllers/ProductController.php && php -l app/Models/Measure.php && php -l app/Models/Product.php && echo [pre-commit] Ejecutando pruebas de catalogos... && php artisan test --filter MeasureCatalogAccessTest && php artisan test --filter ProductCatalogAccessTest && echo [pre-commit] OK
