[barandrest]
yourserver.example.com ansible_user=deploy ansible_port=22

[barandrest:vars]
# Ruta donde se desplegará la aplicación
deploy_path=/var/www/barandrest
# Ruta a la clave privada que usarás desde el controlador Ansible local
ansible_ssh_private_key_file={{ playbook_dir }}/../deploy/keys/deploy_key

# Clave pública generada (añadela al servidor en ~/.ssh/authorized_keys)
# Public key (deploy/keys/deploy_key.pub):
# ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDW1xPDXrYtvjFVK75bsrkbiyEicSYt1UypfGRdY3x09I0o+RC1br8gCJPuziubEn/sX22udOVL6BY8T2Y92ppV2rZ3M6t0UZiz+pRChq1vcBkaqwV8idnLD5bKSSy7xZ5Y9WzccWMAZDpT2+gv/6XbXKaSvwdPByVptS71rB+lKQU8xQ7kUY+yHAPsM7lLMKP47vjQvi46ly7qpsSGT5klpPg8E9mIQA6ksjFSC95Fydp4GFqVBkKp+38DZnh/D/uONvXYZzDGHAT0nKBzQNpuKhmgR4+cdVsvaHAHM9uQo1JrHBOiSs5PEz46oJ33HbfL2xsLvH5vvlZCMnfvHB7BZBRXFWMu7HYw39Zm/m21i/2n1XrOgzK0SfQYTv6WE1c0Zb5564cQTDuxUc3y8I0oXizbFzw7ijGM2R+nqZhlf369Nv7swDtHGeg+ogdraJWY5bSBSwx1SLkon4JrUyDAKdw6XfXHJJ/nDeqcWYT0lgk5MqvjoACUYiijWwZsoGo6WZoTRPVH2ceWPh5VxgsXJG3YoY1xkQYxCMsTOr6QjCXmsKp3Ufl1n0dJyXB6a1+fOzNfmsnzieDK58m78naevbJd9lNnNfE6EnBa2LYDEx/zHLE9e8AeqyspfcvlOiwwipOYlYANjwpOGNjo0BowDCKfw4ynVOTPzE0A/xParQ== barandrest-deploy-key